name: Project builder
on: [push, pull_request]
jobs:
  build:
    name: Compile project
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@v3
      
      - name: Install dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libopencv-dev dia doxygen doxygen-latex graphviz
          execute_install_scripts: true
          version: 1.0
      
      - name: Build project
        run: ./build.sh
      
      - name: Upload docs as an artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: build/doc_doxygen/html

          
  tests:
    name: Test project
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Install dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libopencv-dev dia doxygen doxygen-latex graphviz
          execute_install_scripts: true
          version: 1.0
      
      - name: Build project
        run: |
              ./build.sh test
      - name: Test project
        run: |
              cd build
              ctest
  
  deploy:
    name: Deploy documentation as an artifact
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v4
