name: Project builder
on: [push, pull_request]
jobs:
  build:
    name: Compile project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: |
          sudo apt-get -qq update
          sudo apt-get -qq install ninja-build libopencv-dev
      - run: ./build.sh
