name: Project builder
on: [push, pull_request]
jobs:
  build:
    name: Compile project
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: |
          sudo apt-get -qq update
          sudo apt-get -qq install libopencv-dev
      - run: ./build.sh
  tests:
    name: Test project
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: ./bash.sh test
              cd build
              ctest
